// TODO(backend): swap for queries from `@/lib/db/queries/projects` once Backend ships P1.15.

import type { Project } from './types';

export const SAMPLE_PROJECTS: readonly Project[] = [
  {
    id: 'pr_001',
    code: 'APR-FY26-001',
    name: 'Marigold spring launch',
    clientId: 'cl_001',
    clientName: 'Marigold Coffee Roasters',
    status: 'active',
    dbStatus: 'active',
    billingModel: 'fixed_fee',
    leadEmployeeId: null,
    leadName: 'Riya Patel',
    accountManagerId: null,
    accountManagerName: '—',
    clientContactId: null,
    clientContactName: null,
    parentProjectId: null,
    subProjectCount: 0,
    subFeeSumPaise: 0n,
    linkedInvoiceCount: 0,
    feePaise: 12_50_000_00n,
    startedAt: new Date('2026-03-01'),
    endsAt: new Date('2026-06-30'),
    deliverablesTotal: 12,
    deliverablesDone: 7,
    milestonesTotal: 4,
    milestonesDone: 2,
    documentsCount: 9,
    notes: 'Phase 1 (creative) signed off. Phase 2 (rollout) in progress.',
  },
  {
    id: 'pr_002',
    code: 'APR-FY26-002',
    name: 'Northwind Marina launch film',
    clientId: 'cl_002',
    clientName: 'Northwind Realty',
    status: 'active',
    dbStatus: 'active',
    billingModel: 'milestone',
    leadEmployeeId: null,
    leadName: 'Karan Shah',
    accountManagerId: null,
    accountManagerName: '—',
    clientContactId: null,
    clientContactName: null,
    parentProjectId: null,
    subProjectCount: 0,
    subFeeSumPaise: 0n,
    linkedInvoiceCount: 0,
    feePaise: 28_00_000_00n,
    startedAt: new Date('2026-04-10'),
    endsAt: new Date('2026-08-15'),
    deliverablesTotal: 6,
    deliverablesDone: 2,
    milestonesTotal: 5,
    milestonesDone: 1,
    documentsCount: 5,
    notes: null,
  },
  {
    id: 'pr_003',
    code: 'APR-FY26-003',
    name: 'Solace brand identity',
    clientId: 'cl_003',
    clientName: 'Solace Wellness',
    status: 'active',
    dbStatus: 'active',
    billingModel: 'fixed_fee',
    leadEmployeeId: null,
    leadName: 'Riya Patel',
    accountManagerId: null,
    accountManagerName: '—',
    clientContactId: null,
    clientContactName: null,
    parentProjectId: null,
    subProjectCount: 0,
    subFeeSumPaise: 0n,
    linkedInvoiceCount: 0,
    feePaise: 4_50_000_00n,
    startedAt: new Date('2026-05-05'),
    endsAt: new Date('2026-07-05'),
    deliverablesTotal: 8,
    deliverablesDone: 3,
    milestonesTotal: 3,
    milestonesDone: 1,
    documentsCount: 3,
    notes: 'Awaiting client feedback on round 2 logo concepts.',
  },
  {
    id: 'pr_004',
    code: 'APR-FY26-004',
    name: 'Verde Q2 performance creative',
    clientId: 'cl_005',
    clientName: 'Verde Skincare',
    status: 'active',
    dbStatus: 'active',
    billingModel: 'retainer',
    leadEmployeeId: null,
    leadName: 'Aarav Singh',
    accountManagerId: null,
    accountManagerName: '—',
    clientContactId: null,
    clientContactName: null,
    parentProjectId: null,
    subProjectCount: 0,
    subFeeSumPaise: 0n,
    linkedInvoiceCount: 0,
    feePaise: 6_00_000_00n,
    startedAt: new Date('2026-04-01'),
    endsAt: null,
    deliverablesTotal: 24,
    deliverablesDone: 16,
    milestonesTotal: 3,
    milestonesDone: 2,
    documentsCount: 11,
    notes: 'Monthly retainer. Renewal opt-in clause every quarter.',
  },
  {
    id: 'pr_005',
    code: 'APR-FY25-038',
    name: 'Northwind website refresh',
    clientId: 'cl_002',
    clientName: 'Northwind Realty',
    status: 'delivered',
    dbStatus: 'completed',
    billingModel: 'fixed_fee',
    leadEmployeeId: null,
    leadName: 'Karan Shah',
    accountManagerId: null,
    accountManagerName: '—',
    clientContactId: null,
    clientContactName: null,
    parentProjectId: null,
    subProjectCount: 0,
    subFeeSumPaise: 0n,
    linkedInvoiceCount: 0,
    feePaise: 9_75_000_00n,
    startedAt: new Date('2025-11-12'),
    endsAt: new Date('2026-02-28'),
    deliverablesTotal: 14,
    deliverablesDone: 14,
    milestonesTotal: 4,
    milestonesDone: 4,
    documentsCount: 18,
    notes: 'Final retainer hand-off complete. Warranty period ends Aug 2026.',
  },
  {
    id: 'pr_006',
    code: 'APR-FY26-005',
    name: 'Verde packaging redesign',
    clientId: 'cl_005',
    clientName: 'Verde Skincare',
    status: 'on_hold',
    dbStatus: 'on_hold',
    billingModel: 'fixed_fee',
    leadEmployeeId: null,
    leadName: 'Aarav Singh',
    accountManagerId: null,
    accountManagerName: '—',
    clientContactId: null,
    clientContactName: null,
    parentProjectId: null,
    subProjectCount: 0,
    subFeeSumPaise: 0n,
    linkedInvoiceCount: 0,
    feePaise: 7_25_000_00n,
    startedAt: new Date('2026-03-15'),
    endsAt: new Date('2026-08-31'),
    deliverablesTotal: 9,
    deliverablesDone: 2,
    milestonesTotal: 3,
    milestonesDone: 1,
    documentsCount: 4,
    notes: 'Paused while client locks in new SKU strategy.',
  },
];

export function findSampleProject(id: string): Project | undefined {
  return SAMPLE_PROJECTS.find((project) => project.id === id);
}
