-- ───────────────────────────────────────────────────────────────────────────
-- Generated by drizzle-kit. Do not edit by hand — re-run `npm run db:generate`.
--
-- Deferred to a later migration (require auth context):
--   • RLS: ALTER TABLE ... ENABLE ROW LEVEL SECURITY + policies per role
--   • auth.user_role() helper function (reads role from `users` for auth.uid())
--   • Trigger function log_activity() + triggers on users/clients/contacts/
--     documents/client_activities → activity_log
--   • Trigger on auth.users INSERT → public.users (Phase 1 task P1.06 step 6)
--   • Storage bucket policies (P1.11)
-- ───────────────────────────────────────────────────────────────────────────

CREATE TYPE "public"."client_activity_type" AS ENUM('meeting', 'email', 'call', 'note');--> statement-breakpoint
CREATE TYPE "public"."client_status" AS ENUM('prospect', 'active', 'inactive');--> statement-breakpoint
CREATE TYPE "public"."document_bucket" AS ENUM('public-docs', 'internal-docs', 'restricted-docs', 'restricted-kyc');--> statement-breakpoint
CREATE TYPE "public"."document_visibility" AS ENUM('public', 'internal', 'restricted', 'kyc');--> statement-breakpoint
CREATE TYPE "public"."user_role" AS ENUM('partner', 'admin', 'manager', 'accountant', 'employee', 'viewer');--> statement-breakpoint
CREATE TABLE "activity_log" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	"actor_id" uuid,
	"entity_type" text NOT NULL,
	"entity_id" uuid NOT NULL,
	"action" text NOT NULL,
	"changes" jsonb NOT NULL
);
--> statement-breakpoint
CREATE TABLE "client_activities" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	"created_by" uuid,
	"updated_by" uuid,
	"client_id" uuid NOT NULL,
	"contact_id" uuid,
	"type" "client_activity_type" NOT NULL,
	"summary" text NOT NULL,
	"occurred_at" timestamp with time zone NOT NULL,
	"follow_up_at" timestamp with time zone,
	"recorded_by" uuid
);
--> statement-breakpoint
CREATE TABLE "client_activity_attachments" (
	"activity_id" uuid NOT NULL,
	"document_id" uuid NOT NULL,
	CONSTRAINT "client_activity_attachments_activity_id_document_id_pk" PRIMARY KEY("activity_id","document_id")
);
--> statement-breakpoint
CREATE TABLE "client_activity_attendees" (
	"activity_id" uuid NOT NULL,
	"contact_id" uuid NOT NULL,
	CONSTRAINT "client_activity_attendees_activity_id_contact_id_pk" PRIMARY KEY("activity_id","contact_id")
);
--> statement-breakpoint
CREATE TABLE "client_contacts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	"created_by" uuid,
	"updated_by" uuid,
	"client_id" uuid NOT NULL,
	"name" text NOT NULL,
	"role" text,
	"email" text,
	"phone" text,
	"is_primary" boolean DEFAULT false NOT NULL,
	"notes" text
);
--> statement-breakpoint
CREATE TABLE "clients" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	"created_by" uuid,
	"updated_by" uuid,
	"name" text NOT NULL,
	"industry" text,
	"status" "client_status" DEFAULT 'active' NOT NULL,
	"account_manager_id" uuid,
	"gstin" text,
	"pan" text,
	"notes" text
);
--> statement-breakpoint
CREATE TABLE "documents" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	"created_by" uuid,
	"updated_by" uuid,
	"entity_type" text NOT NULL,
	"entity_id" uuid NOT NULL,
	"bucket" "document_bucket" NOT NULL,
	"storage_path" text NOT NULL,
	"visibility" "document_visibility" NOT NULL,
	"category" text,
	"original_filename" text NOT NULL,
	"mime_type" text NOT NULL,
	"size_bytes" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "organizations" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	"created_by" uuid,
	"updated_by" uuid,
	"legal_name" text NOT NULL,
	"display_name" text NOT NULL,
	"gstin" text,
	"pan" text,
	"registered_address" text
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	"role" "user_role" DEFAULT 'employee' NOT NULL,
	"full_name" text NOT NULL,
	"email" text NOT NULL,
	"masked_pan" text,
	"masked_aadhaar" text,
	CONSTRAINT "users_email_unique" UNIQUE("email")
);
--> statement-breakpoint
ALTER TABLE "client_activities" ADD CONSTRAINT "client_activities_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "client_activities" ADD CONSTRAINT "client_activities_contact_id_client_contacts_id_fk" FOREIGN KEY ("contact_id") REFERENCES "public"."client_contacts"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "client_activities" ADD CONSTRAINT "client_activities_recorded_by_users_id_fk" FOREIGN KEY ("recorded_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "client_activity_attachments" ADD CONSTRAINT "client_activity_attachments_activity_id_client_activities_id_fk" FOREIGN KEY ("activity_id") REFERENCES "public"."client_activities"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "client_activity_attachments" ADD CONSTRAINT "client_activity_attachments_document_id_documents_id_fk" FOREIGN KEY ("document_id") REFERENCES "public"."documents"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "client_activity_attendees" ADD CONSTRAINT "client_activity_attendees_activity_id_client_activities_id_fk" FOREIGN KEY ("activity_id") REFERENCES "public"."client_activities"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "client_activity_attendees" ADD CONSTRAINT "client_activity_attendees_contact_id_client_contacts_id_fk" FOREIGN KEY ("contact_id") REFERENCES "public"."client_contacts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "client_contacts" ADD CONSTRAINT "client_contacts_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "clients" ADD CONSTRAINT "clients_account_manager_id_users_id_fk" FOREIGN KEY ("account_manager_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "activity_log_entity_type_entity_id_created_at_index" ON "activity_log" USING btree ("entity_type","entity_id","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "activity_log_actor_id_created_at_index" ON "activity_log" USING btree ("actor_id","created_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "client_activities_client_id_occurred_at_index" ON "client_activities" USING btree ("client_id","occurred_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "client_activities_type_index" ON "client_activities" USING btree ("type");--> statement-breakpoint
CREATE INDEX "client_activities_follow_up_at_index" ON "client_activities" USING btree ("follow_up_at");--> statement-breakpoint
CREATE INDEX "client_activity_attachments_document_id_index" ON "client_activity_attachments" USING btree ("document_id");--> statement-breakpoint
CREATE INDEX "client_activity_attendees_contact_id_index" ON "client_activity_attendees" USING btree ("contact_id");--> statement-breakpoint
CREATE INDEX "client_contacts_client_id_index" ON "client_contacts" USING btree ("client_id");--> statement-breakpoint
CREATE INDEX "client_contacts_email_index" ON "client_contacts" USING btree ("email");--> statement-breakpoint
CREATE INDEX "clients_status_index" ON "clients" USING btree ("status");--> statement-breakpoint
CREATE INDEX "clients_account_manager_id_index" ON "clients" USING btree ("account_manager_id");--> statement-breakpoint
CREATE INDEX "clients_name_index" ON "clients" USING btree ("name");--> statement-breakpoint
CREATE INDEX "documents_entity_type_entity_id_index" ON "documents" USING btree ("entity_type","entity_id");--> statement-breakpoint
CREATE INDEX "documents_bucket_index" ON "documents" USING btree ("bucket");--> statement-breakpoint
CREATE INDEX "documents_visibility_index" ON "documents" USING btree ("visibility");--> statement-breakpoint
CREATE INDEX "users_email_index" ON "users" USING btree ("email");--> statement-breakpoint
CREATE INDEX "users_role_index" ON "users" USING btree ("role");