// TODO(backend): swap these fixtures for real queries from `@/lib/db/queries/clients`
// (or server actions that wrap them) once Backend ships P1.12. Until then the UI shell
// reads from this constant so list/detail layouts can be reviewed.

import type { Client } from './types';

export const SAMPLE_CLIENTS: readonly Client[] = [
  {
    id: 'cl_001',
    name: 'Marigold Coffee Roasters',
    industry: 'F&B',
    status: 'active',
    priority: 'strategic',
    accountManager: 'Riya Patel',
    gstin: '27ABCDE1234F1Z5',
    pan: 'ABCDE1234F',
    city: 'Mumbai',
    onboardedAt: new Date('2024-04-12'),
    lastActivityAt: new Date('2026-05-18'),
    tags: ['retainer', 'social', 'packaging'],
    pocs: [
      {
        id: 'poc_001',
        name: 'Anjali Mehta',
        title: 'Marketing Head',
        email: 'anjali@marigold.example',
        phone: '+91 98200 11111',
        isPrimary: true,
      },
      {
        id: 'poc_002',
        name: 'Vikram Joshi',
        title: 'Founder',
        email: 'vikram@marigold.example',
        phone: '+91 98200 22222',
        isPrimary: false,
      },
    ],
    projectsCount: 3,
    documentsCount: 18,
    notes: 'Quarterly campaign cadence. SOW renewed March 2026.',
  },
  {
    id: 'cl_002',
    name: 'Northwind Realty',
    industry: 'Real Estate',
    status: 'active',
    priority: 'high',
    accountManager: 'Karan Shah',
    gstin: '27FGHIJ5678K1Z2',
    pan: 'FGHIJ5678K',
    city: 'Pune',
    onboardedAt: new Date('2025-01-08'),
    lastActivityAt: new Date('2026-05-12'),
    tags: ['launch', 'video'],
    pocs: [
      {
        id: 'poc_003',
        name: 'Suresh Kapoor',
        title: 'Director of Marketing',
        email: 'suresh@northwind.example',
        phone: '+91 98300 33333',
        isPrimary: true,
      },
    ],
    projectsCount: 2,
    documentsCount: 11,
    notes: null,
  },
  {
    id: 'cl_003',
    name: 'Solace Wellness',
    industry: 'Wellness',
    status: 'onboarding',
    priority: 'medium',
    accountManager: 'Riya Patel',
    gstin: null,
    pan: 'KLMNO9012P',
    city: 'Bengaluru',
    onboardedAt: new Date('2026-05-02'),
    lastActivityAt: new Date('2026-05-20'),
    tags: ['branding'],
    pocs: [
      {
        id: 'poc_004',
        name: 'Meera Iyer',
        title: 'Founder',
        email: 'meera@solace.example',
        phone: '+91 99100 44444',
        isPrimary: true,
      },
    ],
    projectsCount: 1,
    documentsCount: 4,
    notes: 'Logo + brand book underway. KYC pending — chase before next invoice.',
  },
  {
    id: 'cl_004',
    name: 'Atlas Logistics',
    industry: 'Logistics',
    status: 'inactive',
    priority: 'low',
    accountManager: 'Karan Shah',
    gstin: '27QRSTU3456L1Z9',
    pan: 'QRSTU3456L',
    city: 'Chennai',
    onboardedAt: new Date('2023-09-21'),
    lastActivityAt: new Date('2025-12-04'),
    tags: ['paused'],
    pocs: [
      {
        id: 'poc_005',
        name: 'Devika Rao',
        title: 'Brand Manager',
        email: 'devika@atlas.example',
        phone: '+91 98400 55555',
        isPrimary: true,
      },
    ],
    projectsCount: 0,
    documentsCount: 22,
    notes: 'Paused after Q3 2025. Devika to confirm revival by EOY.',
  },
  {
    id: 'cl_005',
    name: 'Verde Skincare',
    industry: 'D2C',
    status: 'active',
    priority: 'high',
    accountManager: 'Aarav Singh',
    gstin: '27VWXYZ7890M1Z1',
    pan: 'VWXYZ7890M',
    city: 'Mumbai',
    onboardedAt: new Date('2025-07-15'),
    lastActivityAt: new Date('2026-05-21'),
    tags: ['retainer', 'performance', 'creative'],
    pocs: [
      {
        id: 'poc_006',
        name: 'Tara Bhatt',
        title: 'Growth Lead',
        email: 'tara@verde.example',
        phone: '+91 99300 66666',
        isPrimary: true,
      },
    ],
    projectsCount: 4,
    documentsCount: 31,
    notes: null,
  },
  {
    id: 'cl_006',
    name: 'Crimson Studios',
    industry: 'Media',
    status: 'archived',
    priority: 'low',
    accountManager: 'Riya Patel',
    gstin: null,
    pan: null,
    city: 'Delhi',
    onboardedAt: new Date('2022-11-03'),
    lastActivityAt: new Date('2024-03-14'),
    tags: [],
    pocs: [],
    projectsCount: 0,
    documentsCount: 5,
    notes: 'Wound down in early 2024.',
  },
];

export function findSampleClient(id: string): Client | undefined {
  return SAMPLE_CLIENTS.find((client) => client.id === id);
}
