// TODO(backend): swap for queries from `@/lib/db/queries/employees` once Backend ships P1.14.
// KYC fields here are MASKED only — the real PAN/Aadhaar live in restricted-kyc storage.

import type { Employee } from './types';

export const SAMPLE_EMPLOYEES: readonly Employee[] = [
  {
    id: 'em_001',
    fullName: 'Riya Patel',
    designation: 'Partner — Client',
    department: 'leadership',
    employmentType: 'full_time',
    status: 'active',
    workEmail: 'riya@apar.example',
    phone: '+91 99001 10001',
    city: 'Mumbai',
    joinedAt: new Date('2019-06-01'),
    exitedAt: null,
    reportsTo: null,
    panMasked: 'XXXXX1234R',
    aadhaarMasked: 'XXXX XXXX 1234',
    documentsCount: 12,
    notes: null,
  },
  {
    id: 'em_002',
    fullName: 'Karan Shah',
    designation: 'Partner — Strategy',
    department: 'leadership',
    employmentType: 'full_time',
    status: 'active',
    workEmail: 'karan@apar.example',
    phone: '+91 99002 10002',
    city: 'Mumbai',
    joinedAt: new Date('2019-06-01'),
    exitedAt: null,
    reportsTo: null,
    panMasked: 'XXXXX5678K',
    aadhaarMasked: 'XXXX XXXX 5678',
    documentsCount: 11,
    notes: null,
  },
  {
    id: 'em_003',
    fullName: 'Aarav Singh',
    designation: 'Growth Lead',
    department: 'growth',
    employmentType: 'full_time',
    status: 'active',
    workEmail: 'aarav@apar.example',
    phone: '+91 99003 10003',
    city: 'Mumbai',
    joinedAt: new Date('2022-09-15'),
    exitedAt: null,
    reportsTo: 'Riya Patel',
    panMasked: 'XXXXX9012A',
    aadhaarMasked: null,
    documentsCount: 8,
    notes: null,
  },
  {
    id: 'em_004',
    fullName: 'Tanvi Desai',
    designation: 'Senior Designer',
    department: 'creative',
    employmentType: 'full_time',
    status: 'active',
    workEmail: 'tanvi@apar.example',
    phone: '+91 99004 10004',
    city: 'Mumbai',
    joinedAt: new Date('2023-02-20'),
    exitedAt: null,
    reportsTo: 'Karan Shah',
    panMasked: 'XXXXX3456T',
    aadhaarMasked: 'XXXX XXXX 3456',
    documentsCount: 7,
    notes: null,
  },
  {
    id: 'em_005',
    fullName: 'Devansh Roy',
    designation: 'Project Manager',
    department: 'operations',
    employmentType: 'full_time',
    status: 'notice',
    workEmail: 'devansh@apar.example',
    phone: '+91 99005 10005',
    city: 'Pune',
    joinedAt: new Date('2024-01-08'),
    exitedAt: null,
    reportsTo: 'Karan Shah',
    panMasked: 'XXXXX7890D',
    aadhaarMasked: null,
    documentsCount: 5,
    notes: 'Notice period started 2026-05-01. Last working day 2026-07-31.',
  },
  {
    id: 'em_006',
    fullName: 'Priya Nair',
    designation: 'Accountant',
    department: 'finance',
    employmentType: 'full_time',
    status: 'active',
    workEmail: 'priya@apar.example',
    phone: '+91 99006 10006',
    city: 'Mumbai',
    joinedAt: new Date('2021-11-15'),
    exitedAt: null,
    reportsTo: 'Riya Patel',
    panMasked: 'XXXXX1122P',
    aadhaarMasked: 'XXXX XXXX 1122',
    documentsCount: 9,
    notes: null,
  },
  {
    id: 'em_007',
    fullName: 'Ishaan Kapoor',
    designation: 'Intern — Creative',
    department: 'creative',
    employmentType: 'intern',
    status: 'active',
    workEmail: 'ishaan@apar.example',
    phone: '+91 99007 10007',
    city: 'Mumbai',
    joinedAt: new Date('2026-04-01'),
    exitedAt: null,
    reportsTo: 'Tanvi Desai',
    panMasked: null,
    aadhaarMasked: null,
    documentsCount: 2,
    notes: '6-month internship ends 2026-09-30.',
  },
  {
    id: 'em_008',
    fullName: 'Ananya Kulkarni',
    designation: 'Brand Strategist',
    department: 'strategy',
    employmentType: 'full_time',
    status: 'separated',
    workEmail: 'ananya@apar.example',
    phone: '+91 99008 10008',
    city: 'Bengaluru',
    joinedAt: new Date('2020-08-12'),
    exitedAt: new Date('2025-09-30'),
    reportsTo: 'Karan Shah',
    panMasked: 'XXXXX3344A',
    aadhaarMasked: 'XXXX XXXX 3344',
    documentsCount: 14,
    notes: 'Separation cordial. Eligible for rehire.',
  },
];

export function findSampleEmployee(id: string): Employee | undefined {
  return SAMPLE_EMPLOYEES.find((employee) => employee.id === id);
}
