/**
 * Re-export of every Drizzle-inferred table type so Frontend can
 * `import type { Client, Vendor, ... } from '@/types/db'` without
 * reaching into `src/lib/db/schema/*` directly.
 *
 * Pattern (per F7 of SESSION-COORDINATION):
 *   - Schema is the source of truth (in `src/lib/db/schema/`).
 *   - This file is a thin alias surface — when a new table lands,
 *     add its `Select` and `Insert` types here.
 *   - Server-only types (auth context, etc.) belong elsewhere; this
 *     file is safe to import from client components.
 */

import type {
  AdvanceAllocation,
  AuditLog,
  Bill,
  BillLine,
  BillingSettings,
  Client,
  CreditNote,
  CreditNoteLine,
  CustomerAdvance,
  Employee,
  EntityActivityLog,
  EntityAddress,
  EntityBankAccount,
  EntityContact,
  EntityCustomValue,
  EntityDocument,
  EntityRelationship,
  EntityTaxIdentifier,
  EntityType,
  Estimate,
  EstimateInvoiceLink,
  EstimateLine,
  FormField,
  FormFieldChange,
  FormTemplate,
  Invoice,
  InvoiceLine,
  InvoiceReminderLogEntry,
  NewAdvanceAllocation,
  NewAuditLog,
  NewBill,
  NewBillLine,
  NewBillingSettings,
  NewClient,
  NewCreditNote,
  NewCreditNoteLine,
  NewCustomerAdvance,
  NewEmployee,
  NewEntityActivityLog,
  NewEntityAddress,
  NewEntityBankAccount,
  NewEntityContact,
  NewEntityCustomValue,
  NewEntityDocument,
  NewEntityRelationship,
  NewEntityTaxIdentifier,
  NewEstimate,
  NewEstimateInvoiceLink,
  NewEstimateLine,
  NewFormField,
  NewFormFieldChange,
  NewFormTemplate,
  NewInvoice,
  NewInvoiceLine,
  NewInvoiceReminderLogEntry,
  NewPartyBillingProfile,
  NewPaymentAllocation,
  NewProject,
  NewReceipt,
  NewReceiptVoucher,
  NewRefundVoucher,
  NewRoleCapability,
  NewServiceItem,
  NewTdsReferenceSection,
  NewUserTablePreference,
  NewVendor,
  PartyBillingProfile,
  PaymentAllocation,
  Project,
  Receipt,
  ReceiptVoucher,
  RefundVoucher,
  RoleCapability,
  ServiceItem,
  TdsReferenceSection,
  UserTablePreference,
  Vendor,
} from '@/lib/db/schema';

export type {
  // Audit
  AuditLog,
  NewAuditLog,
  // Principal entities
  Client,
  NewClient,
  Vendor,
  NewVendor,
  Employee,
  NewEmployee,
  Project,
  NewProject,
  // Polymorphic shared
  EntityType,
  // Polymorphic children
  EntityContact,
  NewEntityContact,
  EntityAddress,
  NewEntityAddress,
  EntityBankAccount,
  NewEntityBankAccount,
  EntityTaxIdentifier,
  NewEntityTaxIdentifier,
  EntityDocument,
  NewEntityDocument,
  EntityRelationship,
  NewEntityRelationship,
  EntityCustomValue,
  NewEntityCustomValue,
  EntityActivityLog,
  NewEntityActivityLog,
  // Form Builder
  FormTemplate,
  NewFormTemplate,
  FormField,
  NewFormField,
  FormFieldChange,
  NewFormFieldChange,
  // RBAC
  RoleCapability,
  NewRoleCapability,
  // User-facing state
  UserTablePreference,
  NewUserTablePreference,
  // Billing (Phase 1)
  ServiceItem,
  NewServiceItem,
  PartyBillingProfile,
  NewPartyBillingProfile,
  Invoice,
  NewInvoice,
  InvoiceLine,
  NewInvoiceLine,
  Estimate,
  NewEstimate,
  EstimateLine,
  NewEstimateLine,
  EstimateInvoiceLink,
  NewEstimateInvoiceLink,
  CreditNote,
  NewCreditNote,
  CreditNoteLine,
  NewCreditNoteLine,
  Bill,
  NewBill,
  BillLine,
  NewBillLine,
  Receipt,
  NewReceipt,
  PaymentAllocation,
  NewPaymentAllocation,
  CustomerAdvance,
  NewCustomerAdvance,
  AdvanceAllocation,
  NewAdvanceAllocation,
  ReceiptVoucher,
  NewReceiptVoucher,
  RefundVoucher,
  NewRefundVoucher,
  TdsReferenceSection,
  NewTdsReferenceSection,
  InvoiceReminderLogEntry,
  NewInvoiceReminderLogEntry,
  BillingSettings,
  NewBillingSettings,
};

// Re-export enum value arrays for runtime checks (Zod refinements, etc.)
export {
  addressKindEnum,
  bankAccountTypeEnum,
  billAttributionEnum,
  billStateEnum,
  contractStatusEnum,
  creditNoteStateEnum,
  documentKindEnum,
  documentStatusEnum,
  employeeStatusEnum,
  employmentTypeEnum,
  entityRelationshipKindEnum,
  entityTypeEnum,
  estimateLinkKindEnum,
  estimateStateEnum,
  formFieldChangeKindEnum,
  formFieldTypeEnum,
  gatewayDefaultEnum,
  invoiceStateEnum,
  partyDefaultPaymentMethodEnum,
  projectStatusEnum,
  receiptMethodEnum,
  reminderChannelEnum,
  reminderStatusEnum,
  taxIdentifierKindEnum,
  userRoleEnum,
  vendorStatusEnum,
} from '@/lib/db/schema';
