'use server';

import { and, eq, gte, lte, sql } from 'drizzle-orm';
import { z } from 'zod';

import { db } from '@/lib/db/client';
import { bills, entityTaxIdentifiers, vendors } from '@/lib/db/schema';
import { requireCapability } from '@/lib/rbac';
import { getActorContext } from '@/lib/server/actor';

/**
 * TDS Form 26Q — quarterly TDS return for non-salary deductions
 * (salary is Form 24Q). Phase 8.2.
 *
 * Emits a CSV mapping to the NSDL/TIN-FC RPU template. The actual
 * .fvu file is generated by the RPU utility from this CSV (offline);
 * we don't construct the binary directly because the RPU's validation
 * is the source of truth.
 *
 * Header columns map 1:1 to RPU columns:
 *   - Section under which deducted (e.g. 194J)
 *   - Deductee PAN
 *   - Deductee name
 *   - Date of deduction (YYYY-MM-DD)
 *   - Amount paid / credited (rupees)
 *   - TDS amount (rupees)
 *   - TDS rate (%)
 *
 * TODO(human): the RPU CSV format also asks for a few derived fields
 * (challan-bsr, challan-serial, challan-date) that we don't yet
 * capture — they live on the bank payment side. Add a tds_challans
 * table + capture in the dashboard's "TDS payment" flow before the
 * first quarterly filing. For now this exports the deduction-side
 * data only; the CA fills in challan rows manually in the RPU UI.
 */

const QuarterSchema = z.enum(['Q1', 'Q2', 'Q3', 'Q4']);

const Tds26qInputSchema = z.object({
  /** FY label like '2025-26'. */
  fyLabel: z.string().regex(/^\d{4}-\d{2}$/),
  quarter: QuarterSchema,
});

export type Tds26qInput = z.input<typeof Tds26qInputSchema>;

export type Tds26qRow = {
  section: string;
  deducteePan: string | null;
  deducteeName: string;
  deductionDate: string;
  amountPaid: number; // rupees
  tdsAmount: number; // rupees
  tdsRate: number; // percent
};

export type Tds26qOutput = {
  fyLabel: string;
  quarter: 'Q1' | 'Q2' | 'Q3' | 'Q4';
  rows: Tds26qRow[];
  csv: string;
};

function quarterToMonths(quarter: 'Q1' | 'Q2' | 'Q3' | 'Q4'): {
  startMonth: number;
  endMonth: number;
} {
  // Indian FY quarters: Q1 Apr-Jun, Q2 Jul-Sep, Q3 Oct-Dec, Q4 Jan-Mar.
  switch (quarter) {
    case 'Q1':
      return { startMonth: 4, endMonth: 6 };
    case 'Q2':
      return { startMonth: 7, endMonth: 9 };
    case 'Q3':
      return { startMonth: 10, endMonth: 12 };
    case 'Q4':
      return { startMonth: 1, endMonth: 3 };
  }
}

function quarterBoundaries(
  fyLabel: string,
  quarter: 'Q1' | 'Q2' | 'Q3' | 'Q4',
): { from: string; to: string } {
  const fyStartYear = Number(fyLabel.slice(0, 4));
  const { startMonth, endMonth } = quarterToMonths(quarter);
  const startCalendarYear = quarter === 'Q4' ? fyStartYear + 1 : fyStartYear;
  const lastDay = new Date(Date.UTC(startCalendarYear, endMonth, 0)).getUTCDate();
  return {
    from: `${startCalendarYear}-${String(startMonth).padStart(2, '0')}-01`,
    to: `${startCalendarYear}-${String(endMonth).padStart(2, '0')}-${String(lastDay).padStart(2, '0')}`,
  };
}

export async function generateTds26q(input: Tds26qInput): Promise<Tds26qOutput> {
  const ctx = await getActorContext();
  requireCapability(ctx, 'view_gst_reports');
  const v = Tds26qInputSchema.parse(input);
  const { from, to } = quarterBoundaries(v.fyLabel, v.quarter);

  // All recorded vendor bills in the quarter with TDS > 0.
  const billRows = await db
    .select({
      billId: bills.id,
      vendorId: bills.vendorId,
      documentDate: bills.documentDate,
      capturedTdsAmountPaise: bills.capturedTdsAmountPaise,
      capturedTdsSection: bills.capturedTdsSection,
      capturedTdsRateBps: bills.capturedTdsRateBps,
      subtotalPaise: bills.subtotalPaise,
      capturedTaxTotalPaise: bills.capturedTaxTotalPaise,
      vendorName: vendors.name,
    })
    .from(bills)
    .leftJoin(vendors, eq(vendors.id, bills.vendorId))
    .where(
      and(
        gte(bills.documentDate, from),
        lte(bills.documentDate, to),
        sql`${bills.state} IN ('recorded', 'partially_paid', 'paid')`,
        sql`${bills.capturedTdsAmountPaise} > 0`,
      ),
    );

  // Look up each vendor's PAN.
  const vendorIds = Array.from(new Set(billRows.map((b) => b.vendorId)));
  const pans =
    vendorIds.length > 0
      ? await db
          .select()
          .from(entityTaxIdentifiers)
          .where(
            and(
              eq(entityTaxIdentifiers.entityType, 'vendor'),
              eq(entityTaxIdentifiers.kind, 'pan'),
              sql`${entityTaxIdentifiers.entityId} IN (${sql.join(
                vendorIds.map((id) => sql`${id}::uuid`),
                sql`, `,
              )})`,
            ),
          )
      : [];
  const panByVendor = new Map<string, string>();
  for (const p of pans) {
    if (p.entityId) panByVendor.set(p.entityId, p.maskedValue);
  }

  const rows: Tds26qRow[] = billRows.map((b) => ({
    section: b.capturedTdsSection ?? 'unknown',
    deducteePan: panByVendor.get(b.vendorId) ?? null,
    deducteeName: b.vendorName ?? `vendor:${b.vendorId}`,
    deductionDate: b.documentDate,
    amountPaid: Number(b.subtotalPaise + b.capturedTaxTotalPaise) / 100,
    tdsAmount: Number(b.capturedTdsAmountPaise) / 100,
    tdsRate: b.capturedTdsRateBps / 100,
  }));

  // CSV emission — RPU template column order.
  const header = [
    'Section',
    'Deductee PAN',
    'Deductee Name',
    'Date of Deduction',
    'Amount Paid (Rs)',
    'TDS Amount (Rs)',
    'TDS Rate (%)',
  ].join(',');

  const body = rows
    .map((r) =>
      [
        r.section,
        r.deducteePan ?? 'PANNOTAVBL',
        // CSV-escape commas + quotes in the name field.
        `"${r.deducteeName.replace(/"/g, '""')}"`,
        r.deductionDate,
        r.amountPaid.toFixed(2),
        r.tdsAmount.toFixed(2),
        r.tdsRate.toFixed(2),
      ].join(','),
    )
    .join('\n');

  const csv = `${header}\n${body}\n`;

  if (rows.length === 0) {
    // Still return the empty CSV — the RPU expects a header row even for
    // a NIL return.
    return { fyLabel: v.fyLabel, quarter: v.quarter, rows: [], csv: `${header}\n` };
  }

  return { fyLabel: v.fyLabel, quarter: v.quarter, rows, csv };
}
