// Fake data for Apar One demo. Mirrors data.jsx from the design bundle.

import type { AppDef, Client, Employee, InboxDoc, Project, Vendor } from './types';

export const APPS: readonly AppDef[] = [
  { id: 'clients', name: 'Clients', icon: 'building', size: { w: 880, h: 580 }, accent: '#E63A1F' },
  { id: 'vendors', name: 'Vendors', icon: 'truck', size: { w: 880, h: 560 }, accent: '#C46A28' },
  {
    id: 'projects',
    name: 'Projects',
    icon: 'folder',
    size: { w: 1080, h: 620 },
    accent: '#7A4E2D',
  },
  {
    id: 'employees',
    name: 'Employees',
    icon: 'users',
    size: { w: 880, h: 560 },
    accent: '#9B3826',
  },
  {
    id: 'attendance',
    name: 'Attendance',
    icon: 'check',
    size: { w: 1180, h: 720 },
    accent: '#2E8F5A',
  },
  { id: 'ledger', name: 'Ledger', icon: 'book', size: { w: 920, h: 580 }, accent: '#5B6677' },
  { id: 'reports', name: 'Reports', icon: 'chart', size: { w: 1000, h: 620 }, accent: '#2E8F5A' },
  { id: 'office', name: 'Office', icon: 'zap', size: { w: 1100, h: 700 }, accent: '#C46A28' },
  {
    id: 'settings',
    name: 'Settings',
    icon: 'settings',
    size: { w: 780, h: 540 },
    accent: '#1A1411',
  },
  // Admin Console — super-admin-only. OsRoot filters this out of the dock and
  // command palette for everyone else; `can(user, 'admin_console', 'view')` rejects too.
  // App id is `admin_console` not `admin` to avoid collision with the role name
  // `admin` once RBAC swaps to the six-role + capability model (Rule 47 + amendment §11).
  {
    id: 'admin_console',
    name: 'Admin Console',
    icon: 'shield',
    size: { w: 980, h: 620 },
    accent: '#E63A1F',
  },
] as const;

export const CLIENTS: readonly Client[] = [
  {
    id: 'c1',
    name: 'Tanishq Mumbai',
    industry: 'Jewellery & Lifestyle',
    manager: 'Ananya Iyer',
    status: 'Active',
    activity: '2h ago',
    logo: 'TM',
    tone: '#B5391E',
  },
  {
    id: 'c2',
    name: 'Lodha Group',
    industry: 'Real Estate',
    manager: 'Rohan Mehta',
    status: 'Active',
    activity: '4h ago',
    logo: 'L',
    tone: '#5B6677',
  },
  {
    id: 'c3',
    name: 'Tribhovandas Bhimji Zaveri',
    industry: 'Jewellery',
    manager: 'Ananya Iyer',
    status: 'Review',
    activity: '1d ago',
    logo: 'TBZ',
    tone: '#7A4E2D',
  },
  {
    id: 'c4',
    name: 'Marico',
    industry: 'FMCG',
    manager: 'Sahil Khurana',
    status: 'Active',
    activity: '3d ago',
    logo: 'M',
    tone: '#2E8F5A',
  },
  {
    id: 'c5',
    name: 'Nykaa',
    industry: 'Beauty & Retail',
    manager: 'Priya Shetty',
    status: 'Pitch',
    activity: '5h ago',
    logo: 'N',
    tone: '#C46A28',
  },
  {
    id: 'c6',
    name: 'Bombay Shaving Company',
    industry: 'D2C Grooming',
    manager: 'Sahil Khurana',
    status: 'Active',
    activity: '6h ago',
    logo: 'BSC',
    tone: '#1A1411',
  },
  {
    id: 'c7',
    name: 'Tata Cliq Luxury',
    industry: 'E-commerce',
    manager: 'Priya Shetty',
    status: 'Onboarding',
    activity: '8h ago',
    logo: 'TC',
    tone: '#D08A1E',
  },
  {
    id: 'c8',
    name: 'Asian Paints — Royale',
    industry: 'Paints',
    manager: 'Rohan Mehta',
    status: 'Paused',
    activity: '2w ago',
    logo: 'AP',
    tone: '#9B3826',
  },
];

export const VENDORS: readonly Vendor[] = [
  {
    id: 'v1',
    name: 'Sundara Lights',
    cat: 'Photographer',
    outstanding: 18_450_000n,
    last: '12 May 26',
  },
  { id: 'v2', name: 'Bombay Print House', cat: 'Printer', outstanding: 0n, last: '28 Apr 26' },
  { id: 'v3', name: 'Cinemavault', cat: 'Production', outstanding: 64_200_000n, last: '14 May 26' },
  { id: 'v4', name: 'Adobe India', cat: 'Software', outstanding: 8_999_900n, last: '01 May 26' },
  {
    id: 'v5',
    name: 'Rangoli Studios',
    cat: 'Illustration',
    outstanding: 6_500_000n,
    last: '09 May 26',
  },
  {
    id: 'v6',
    name: 'Worli Couriers',
    cat: 'Logistics',
    outstanding: 1_240_000n,
    last: '18 May 26',
  },
  { id: 'v7', name: 'Saanvi Voiceovers', cat: 'Talent', outstanding: 0n, last: '02 May 26' },
  {
    id: 'v8',
    name: 'Pixel & Brush',
    cat: 'Animation',
    outstanding: 38_000_000n,
    last: '11 May 26',
  },
  {
    id: 'v9',
    name: 'Mira Translation Co.',
    cat: 'Localisation',
    outstanding: 2_800_000n,
    last: '06 May 26',
  },
  {
    id: 'v10',
    name: 'Bandra Studios',
    cat: 'Photographer',
    outstanding: 14_500_000n,
    last: '15 May 26',
  },
];

export const PROJECTS: readonly Project[] = [
  {
    code: 'APR-26-014',
    name: 'Tanishq Diwali Campaign',
    client: 'Tanishq Mumbai',
    lead: 'AI',
    col: 'Active',
    fee: 480_000_000n,
  },
  {
    code: 'APR-26-021',
    name: 'Lodha Belmondo Brand Refresh',
    client: 'Lodha Group',
    lead: 'RM',
    col: 'Active',
    fee: 620_000_000n,
  },
  {
    code: 'APR-26-018',
    name: 'TBZ Heritage Collection Launch',
    client: 'TBZ',
    lead: 'AI',
    col: 'Review',
    fee: 210_000_000n,
  },
  {
    code: 'APR-26-007',
    name: 'Marico Saffola Reels Campaign',
    client: 'Marico',
    lead: 'SK',
    col: 'Active',
    fee: 185_000_000n,
  },
  {
    code: 'APR-26-022',
    name: 'Nykaa Beauty Awards 2026',
    client: 'Nykaa',
    lead: 'PS',
    col: 'Proposed',
    fee: 350_000_000n,
  },
  {
    code: 'APR-26-005',
    name: 'BSC Razor Launch — Phase II',
    client: 'BSC',
    lead: 'SK',
    col: 'Completed',
    fee: 98_000_000n,
  },
  {
    code: 'APR-26-026',
    name: 'Tata Cliq Luxe Onboarding',
    client: 'Tata Cliq',
    lead: 'PS',
    col: 'Proposed',
    fee: 110_000_000n,
  },
  {
    code: 'APR-25-099',
    name: 'Asian Paints Royale Festive',
    client: 'Asian Paints',
    lead: 'RM',
    col: 'Completed',
    fee: 540_000_000n,
  },
  {
    code: 'APR-26-019',
    name: 'TBZ Polki Shoot — Mehrangarh',
    client: 'TBZ',
    lead: 'AI',
    col: 'Review',
    fee: 72_000_000n,
  },
  {
    code: 'APR-26-024',
    name: 'Tanishq Mia Spring Collection',
    client: 'Tanishq Mumbai',
    lead: 'AI',
    col: 'Active',
    fee: 240_000_000n,
  },
  {
    code: 'APR-26-011',
    name: 'Lodha Park Site Films',
    client: 'Lodha Group',
    lead: 'RM',
    col: 'Active',
    fee: 165_000_000n,
  },
  {
    code: 'APR-26-027',
    name: 'Marico Hair&Care — Q3 Strategy',
    client: 'Marico',
    lead: 'SK',
    col: 'Proposed',
    fee: 90_000_000n,
  },
];

export const EMPLOYEES: readonly Employee[] = [
  {
    id: 'e1',
    name: 'Ananya Iyer',
    role: 'Senior Account Manager',
    dept: 'Accounts',
    tone: '#B5391E',
  },
  { id: 'e2', name: 'Rohan Mehta', role: 'Account Director', dept: 'Accounts', tone: '#5B6677' },
  { id: 'e3', name: 'Priya Shetty', role: 'Strategy Lead', dept: 'Strategy', tone: '#7A4E2D' },
  { id: 'e4', name: 'Sahil Khurana', role: 'Brand Manager', dept: 'Accounts', tone: '#2E8F5A' },
  { id: 'e5', name: 'Vikram Joshi', role: 'Head of Design', dept: 'Creative', tone: '#D08A1E' },
  {
    id: 'e6',
    name: 'Meera Bhattacharya',
    role: 'Copy Director',
    dept: 'Creative',
    tone: '#9B3826',
  },
  { id: 'e7', name: 'Karan Saxena', role: 'Motion Designer', dept: 'Creative', tone: '#1A1411' },
  { id: 'e8', name: 'Riya Sengupta', role: 'Senior Visualiser', dept: 'Creative', tone: '#C46A28' },
  { id: 'e9', name: 'Aditya Rao', role: 'Finance Controller', dept: 'Finance', tone: '#5B6677' },
  { id: 'e10', name: 'Tara Nair', role: 'People & Culture Lead', dept: 'People', tone: '#B5391E' },
];

export const INBOX_DOCS: readonly InboxDoc[] = [
  {
    id: 'd1',
    file: 'TBZ_Mehrangarh_Invoice_05.pdf',
    type: 'Vendor Invoice',
    conf: 'green',
    by: 'Vikram Joshi',
    ago: '12 min ago',
  },
  {
    id: 'd2',
    file: 'Lodha_PO_BMD-2418.pdf',
    type: 'Purchase Order',
    conf: 'green',
    by: 'Rohan Mehta',
    ago: '34 min ago',
  },
  {
    id: 'd3',
    file: 'Marico_Saffola_SOW_v3.pdf',
    type: 'SOW',
    conf: 'amber',
    by: 'Sahil Khurana',
    ago: '1h ago',
  },
  {
    id: 'd4',
    file: 'Cinemavault_Quote_2618.pdf',
    type: 'Vendor Quote',
    conf: 'amber',
    by: 'Karan Saxena',
    ago: '2h ago',
  },
  {
    id: 'd5',
    file: 'Tanishq_Festive_MSA_signed.pdf',
    type: 'Contract',
    conf: 'green',
    by: 'Ananya Iyer',
    ago: '3h ago',
  },
  {
    id: 'd6',
    file: 'Nykaa_Pitch_DraftBrief.pdf',
    type: 'Creative Brief',
    conf: 'red',
    by: 'Priya Shetty',
    ago: '4h ago',
  },
  {
    id: 'd7',
    file: 'BSC_Receipt_Adobe_May.pdf',
    type: 'Expense Receipt',
    conf: 'green',
    by: 'Aditya Rao',
    ago: '6h ago',
  },
  {
    id: 'd8',
    file: 'Pixel&Brush_Invoice_1132.pdf',
    type: 'Vendor Invoice',
    conf: 'amber',
    by: 'Vikram Joshi',
    ago: '1d ago',
  },
];

// The single-entry `LEDGER_TX` seed (15 hand-authored fixtures) was deleted
// in Phase 1 per the brownfield kickoff. Real ledger data will arrive via
// B's `<TransactionList>` against A's `transactions` / `postings` tables
// (LEDGER-SPEC §0.1 + §5). No more fake transaction fixtures in the OS.
