// TODO(backend): swap for queries from `@/lib/db/queries/vendors` once Backend ships P1.13.

import type { Vendor } from './types';

export const SAMPLE_VENDORS: readonly Vendor[] = [
  {
    id: 'vn_001',

    code: 'VN-0001',
    name: 'Kabir Photography',
    category: 'photographer',
    status: 'active',
    gstin: '27ABCDE5678P1Z3',
    pan: 'ABCDE5678P',
    tdsSection: '194J',
    contactName: 'Kabir Sharma',
    contactPhone: '+91 98700 11111',
    city: 'Mumbai',
    outstandingPaise: 1_50_000_00n,
    lastTxnAt: new Date('2026-05-10'),
    documentsCount: 9,
    contractsCount: 1,
    notes: 'Annual retainer. Renewal due Aug 2026.',
  },
  {
    id: 'vn_002',

    code: 'VN-0002',
    name: 'Saffron Prints',
    category: 'printer',
    status: 'active',
    gstin: '27FGHIJ1122Q1Z6',
    pan: 'FGHIJ1122Q',
    tdsSection: '194C',
    contactName: 'Pooja Nair',
    contactPhone: '+91 98800 22222',
    city: 'Pune',
    outstandingPaise: 87_500_00n,
    lastTxnAt: new Date('2026-05-18'),
    documentsCount: 14,
    contractsCount: 0,
    notes: null,
  },
  {
    id: 'vn_003',

    code: 'VN-0003',
    name: 'Notion Labs',
    category: 'software',
    status: 'active',
    gstin: null,
    pan: null,
    tdsSection: 'none',
    contactName: null,
    contactPhone: null,
    city: 'Remote',
    outstandingPaise: 0n,
    lastTxnAt: new Date('2026-04-01'),
    documentsCount: 4,
    contractsCount: 1,
    notes: 'Foreign vendor — no GST/TDS applicable.',
  },
  {
    id: 'vn_004',

    code: 'VN-0004',
    name: 'Mehta Logistics',
    category: 'logistics',
    status: 'active',
    gstin: '27MNOPQ3344R1Z8',
    pan: 'MNOPQ3344R',
    tdsSection: '194C',
    contactName: 'Rohit Mehta',
    contactPhone: '+91 99000 33333',
    city: 'Mumbai',
    outstandingPaise: 25_000_00n,
    lastTxnAt: new Date('2026-05-05'),
    documentsCount: 6,
    contractsCount: 0,
    notes: null,
  },
  {
    id: 'vn_005',

    code: 'VN-0005',
    name: 'Lumière Studios',
    category: 'videographer',
    status: 'inactive',
    gstin: '27STUVW5566X1Z2',
    pan: 'STUVW5566X',
    tdsSection: '194J',
    contactName: 'Aditi Kothari',
    contactPhone: '+91 99100 44444',
    city: 'Bengaluru',
    outstandingPaise: 0n,
    lastTxnAt: new Date('2025-11-12'),
    documentsCount: 11,
    contractsCount: 1,
    notes: 'No work for 6+ months — keep on file.',
  },
  {
    id: 'vn_006',

    code: 'VN-0006',
    name: 'Velocity Studio',
    category: 'agency',
    status: 'active',
    gstin: '27YZABC7788D1Z4',
    pan: 'YZABC7788D',
    tdsSection: '194J',
    contactName: 'Neha Reddy',
    contactPhone: '+91 99200 55555',
    city: 'Hyderabad',
    outstandingPaise: 4_50_000_00n,
    lastTxnAt: new Date('2026-05-21'),
    documentsCount: 22,
    contractsCount: 2,
    notes: 'Subcontractor for performance creative.',
  },
];

export function findSampleVendor(id: string): Vendor | undefined {
  return SAMPLE_VENDORS.find((vendor) => vendor.id === id);
}
